create sequence courier_model_seq start with 1 increment by 50;
create sequence courier_quest_progress_model_seq start with 1 increment by 50;
create sequence quest_claim_model_seq start with 1 increment by 50;
create sequence quest_model_seq start with 1 increment by 50;
create sequence quest_tier_model_seq start with 1 increment by 50;
create table courier_model (id integer not null, email varchar(255), name varchar(255), phone varchar(255), primary key (id));
create table courier_quest_progress_model (courier_id integer, current_tier integer, id integer not null, orders_delivered integer, quest_id integer, primary key (id));
create table quest_claim_model (courier_id integer, id integer not null, quest_id integer, tier_id integer, primary key (id));
create table quest_model (duration integer, id integer not null, created_at varchar(255), created_by varchar(255), name varchar(255), primary key (id));
create table quest_tier_model (id integer not null, order_goal integer, quest_id integer, reward integer not null, tier_number integer, primary key (id));
create sequence courier_model_seq start with 1 increment by 50;
create sequence courier_quest_progress_model_seq start with 1 increment by 50;
create sequence quest_claim_model_seq start with 1 increment by 50;
create sequence quest_model_seq start with 1 increment by 50;
create sequence quest_tier_model_seq start with 1 increment by 50;
create table courier_model (id integer not null, email varchar(255), name varchar(255), phone varchar(255), primary key (id));
create table courier_quest_progress_model (courier_id integer, current_tier integer, id integer not null, orders_delivered integer, quest_id integer, primary key (id));
create table quest_claim_model (courier_id integer, id integer not null, quest_id integer, tier_id integer, primary key (id));
create table quest_model (duration integer, id integer not null, created_at varchar(255), created_by varchar(255), name varchar(255), primary key (id));
create table quest_tier_model (id integer not null, order_goal integer, quest_id integer, reward integer not null, tier_number integer, primary key (id));
create sequence courier_model_seq start with 1 increment by 50;
create sequence courier_quest_progress_model_seq start with 1 increment by 50;
create sequence quest_claim_model_seq start with 1 increment by 50;
create sequence quest_model_seq start with 1 increment by 50;
create sequence quest_tier_model_seq start with 1 increment by 50;
create table courier_model (id integer not null, email varchar(255), name varchar(255), phone varchar(255), primary key (id));
create table courier_quest_progress_model (courier_id integer, current_tier integer, id integer not null, orders_delivered integer, quest_id integer, primary key (id));
create table quest_claim_model (courier_id integer, id integer not null, quest_id integer, tier_id integer, primary key (id));
create table quest_model (duration integer, id integer not null, created_at varchar(255), created_by varchar(255), name varchar(255), primary key (id));
create table quest_tier_model (id integer not null, order_goal integer, quest_id integer, reward integer not null, tier_number integer, primary key (id));
create sequence courier_model_seq start with 1 increment by 50;
create sequence courier_quest_progress_model_seq start with 1 increment by 50;
create sequence quest_claim_model_seq start with 1 increment by 50;
create sequence quest_model_seq start with 1 increment by 50;
create sequence quest_tier_model_seq start with 1 increment by 50;
create table courier_model (id integer not null, email varchar(255), name varchar(255), phone varchar(255), primary key (id));
create table courier_quest_progress_model (courier_id integer, current_tier integer, id integer not null, orders_delivered integer, quest_id integer, primary key (id));
create table quest_claim_model (courier_id integer, id integer not null, quest_id integer, tier_id integer, primary key (id));
create table quest_model (duration integer, id integer not null, created_at varchar(255), created_by varchar(255), name varchar(255), primary key (id));
create table quest_tier_model (id integer not null, order_goal integer, quest_id integer, reward integer not null, tier_number integer, primary key (id));
