version: '3.8'

services:
  main-db:
    image: postgres:latest
    container_name: main-db
    environment:
      POSTGRES_DB: main_database
      POSTGRES_USER: main_user
      POSTGRES_PASSWORD: main_password
    ports:
      - "5432:5432"
    volumes:
      - main-db-data:/var/lib/postgresql/data
    networks:
        - main-network

  test-db:
    image: postgres:latest
    container_name: test-db
    environment:
      POSTGRES_DB: test_database
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    networks:
        - main-network
    depends_on:
      - main-db
    volumes:
      - test-db-data:/var/lib/postgresql/data

  spring-app:
    build:
      context: .
      dockerfile: .dockerfile
    container_name: spring-app
    ports:
      - "8080:8080"
    depends_on:
      - main-db
      - test-db
    networks:
        - main-network


volumes:
  main-db-data:
  test-db-data:

networks:
    main-network:
      driver: bridge

